apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projeto-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: projeto-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: projeto-api
          image: "docker.io/jayjayg/gerenciador-oficina-core:latest"
          resources:
            requests:
              memory: "1200Mi"
              cpu: "250m"
            limits:
              memory: 1536Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: gerenciador-oficina-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
              name: postgres-config