apiVersion: v1
kind: Service
metadata:
  name: gerenciador-oficina-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  # usa Network Load Balancer (EKS Auto Mode)
spec:
  type: LoadBalancer
  selector:
    app: gerenciador-oficina-core-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
