apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerenciador-oficina-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gerenciador-oficina-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gerenciador-oficina-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: gerenciador-oficina-api
          image: "docker.io/jayjayg/gerenciador-oficina-core:latest"
          resources:
            requests:
              memory: "1200Mi"
              cpu: "250m"
            limits:
              memory: 1536Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://gerenciador-oficina-postgres:5432/gerenciador_oficina
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD