apiVersion: v1
kind: Service
metadata:
  name: gerenciador-oficina-core-service
spec:
  type: NodePort
  selector:
    app: gerenciador-oficina-core-api
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081