apiVersion: v1
kind: Service
metadata:
  name: gerenciador-oficina-core-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
spec:
  type: LoadBalancer
  selector:
    app: gerenciador-oficina-core-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081