apiVersion: apps/v1
kind: Deployment
metadata:
  name: projeto-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projeto-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: projeto-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: projeto-api
          image: "docker.io/jayjayg/gerenciador-oficina-core:9"
          resources:
            requests:
              memory: "1200Mi"
              cpu: "250m"
            limits:
              memory: 1536Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8081